Fixes filter dropdown styling
we're holding off on updated @patternfly/patternfly because it fails webpack build, ERROR in ./node_modules/@patternfly/patternfly/utilities/Display/display.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@include pf-utility-builder($pf-u-display-options, $pf-global--breakpoint-list);
        ^
      No mixin named pf-utility-builder